// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYK4dKxyPRTjhPfYG891x-hHlJGguYH1M',
    appId: '1:702645106285:android:c5cbae41738e6f412ff164',
    messagingSenderId: '702645106285',
    projectId: 'altx-6f583',
    storageBucket: 'altx-6f583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT76b6M6YcQT2rfpV9wqEzDYeDLmpvRfI',
    appId: '1:702645106285:ios:14728811343140272ff164',
    messagingSenderId: '702645106285',
    projectId: 'altx-6f583',
    storageBucket: 'altx-6f583.appspot.com',
    iosBundleId: 'com.ec.altx2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcu6REpalHH9rzdn1wjDF-xs8lYXDxqUg',
    appId: '1:702645106285:web:5bc1d5875dcae9ea2ff164',
    messagingSenderId: '702645106285',
    projectId: 'altx-6f583',
    authDomain: 'altx-6f583.firebaseapp.com',
    storageBucket: 'altx-6f583.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT76b6M6YcQT2rfpV9wqEzDYeDLmpvRfI',
    appId: '1:702645106285:ios:14728811343140272ff164',
    messagingSenderId: '702645106285',
    projectId: 'altx-6f583',
    storageBucket: 'altx-6f583.appspot.com',
    iosBundleId: 'com.ec.altx2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcu6REpalHH9rzdn1wjDF-xs8lYXDxqUg',
    appId: '1:702645106285:web:92d2debec176852e2ff164',
    messagingSenderId: '702645106285',
    projectId: 'altx-6f583',
    authDomain: 'altx-6f583.firebaseapp.com',
    storageBucket: 'altx-6f583.appspot.com',
  );

}